title: from selling to co-creating
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.6875
  brandStrength: 1
  lightness: 0.5
  brandColors:
    - '#C3BD9D'
    - '#ECE0C8'
    - '#080A07'
    - '#425E74'
    - '#8F623B'
  rhythmicContrast: 0.75
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: TheCoCreator
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.506
layout_spectrum: 1
