name: TheCoCreator
favicon: null
layout_spectrum: 0.33232518238946795
typography_spectrum: 0.54841
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.8470252114348114
  lightness: 0.7166732172481716
  saturation: 0.7560472839977592
  rhythmicContrast: 0.36406703712418675
purpose: []
