title: from selling to co-creating
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.4680851
  brandStrength: 0.5
  lightness: 0.5
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  rhythmicContrast: 0.25
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: TheCoCreator
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.54841
layout_spectrum: 0.25206
